Change default insertBy implementation to work better with dlists.
ddssff/listlike pull request #18
Opened 2022-11-14 23:16 UTC by AndreasPK

Instead of repeatedly computing head share the `head` computation.
I've also replaced `head` and `tail` by a single call to uncons for similar reasons and
replaced the default uncons implementation for DList by one based on it's pattern synonym.

2022-11-14 23:18 UTC, AndreasPK commented
While looking into https://gitlab.haskell.org/ghc/ghc/-/issues/22425 I noticed this. This helps to pull performance for sort on dlists back to 9.4.2 levels on ghc-9.4.3 and just generally seems better to me independent of the ghc bug.

2022-11-15 10:06 UTC, andreasabel commented on src/Data/ListLike/Base.hs
> +            Just (ys_head,ys_tail) -> case cmp x ys_head of
Style: no snake-case please.  (So far, this code base has a single snake-case id only (`elem_by`) which sneaked in...)
Please us CamlCase or simple identifiers.

2022-11-15 10:06 UTC, andreasabel commented on src/Data/ListLike/DList.hs
> +    D.Cons d_head l_tail -> Prelude.Just (d_head,fromList l_tail)
Please no snake_case.

2022-11-15 10:07 UTC, andreasabel requested changes
Thanks! LGTM except for style issues.

2022-11-15 13:30 UTC, merged

2022-11-15 13:46 UTC, ddssff commented
I hope I didn't merge this prematurely.  Should I leave this repo to you Andreas?

2022-11-15 15:11 UTC, andreasabel commented
I don't mind co-maintainership, I think it helps keeping repos alive.

A "changes requested" should maybe not be ignored, though.  There is branch protection rules that would enforce this, but I am not the repo admin here, I cannot change the settings.

2022-11-16 21:19 UTC, ddssff commented
Ok I will be more careful.  I did that very early in the morning.